#include "highlight.h"

HighLight::HighLight():
    QsciLexerCPP()
{

}

const char *HighLight::keywords(int set) const
{
    if(set == 1)
        //return QsciLexerCPP::keywords(set);
        return
                "word " "WORD "
                "data " ".DATA "
                "half " "HALF "
                "la " "LA "
                "byte " "BYTE "
                "text " "TEXT "
                "nop " "NOP "
                "add " "ADD "
                "addu " "ADDU "
                "and " "AND "
                "nor " "NOR "
                "or " "OR "
                "sub " "SUB "
                "subu " "SUBU "
                "xor " "XOR "
                "slt " "SLT "
                "sltu " "SLTU "
                "mul " "MUL "
                "sll " "SLL "
                "sra " "SRA "
                "srl " "SRL "
                "sllv " "SLLV "
                "srav " "SRAV "
                "srlv " "SRLV "
                "clo " "CLO "
                "clz " "CLZ "
                "mtc1" "MTC1 "
                "div " "DIV "
                "divu " "DIVU "
                "mult " "MULT "
                "multu " "MULTU "
                "madd " "MADD "
                "maddu " "MADDU "
                "msub " "MSUB "
                "mfc0 " "MFC0 "
                "mfc1 " "MFC1 "
                "mtc0 " "MTC0 "
                "jalr " "JALR "
                "mfhi " "MFHI "
                "mflo " "MFLO "
                "mthi " "MTHI "
                "mtlo " "MTLO "
                "jr " "JR "
                "addi " "ADDI "
                "addiu " "ADDIU "
                "andi " "ANDI "
                "ori " "ORI "
                "lui " "LUI "
                "xori " "XORI "
                "slti " "SLTI "
                "sltiu " "SLTIU "
                "beq " "BEQ "
                "bne " "BNE "
                "bgez " "BGEZ "
                "bgezal " "BGEZAL "
                "bgtz " "BGTZ "
                "blez " "BLEZ "
                "bltzal " "BLTZAL "
                "bltz " "BLTZ "
                "lb " "LB "
                "lbu " "LBU "
                "lh " "LH "
                "lhu " "LHU "
                "lw " "LW "
                "sb " "SB "
                "sh " "SH "
                "sw " "SW "
                "j " "J "
                "jal " "JAL "
                "// " "#baseAddr "
                "DataAddre ";
    if(set == 2)
        return
                "$zero " "$ZERO "
                "$at " "$AT "
                "$v0 " "$V0 "
                "$v1 " "$V1 "
                "$a0 " "$A0 "
                "$a1 " "$A1 "
                "$a2 " "$A2 "
                "$a3 " "$A3 "
                "$t0 " "$T0 "
                "$t1 " "$T1 "
                "$t2 " "$T2 "
                "$t3 " "$T3 "
                "$t4 " "$T4 "
                "$t5 " "$T5 "
                "$t6 " "$T6 "
                "$t7 " "$T7 "
                "$s0 " "$S0 "
                "$s1 " "$S1 "
                "$s2 " "$S2 "
                "$s3 " "$S3 "
                "$s4 " "$S4 "
                "$s5 " "$S5 "
                "$s6 " "$S6 "
                "$s7 " "$S7 "
                "$t8 " "$T8 "
                "$t9 " "$T9 "
                "$k0 " "$K0 "
                "$k1 " "$K1 "
                "$gp " "$GP "
                "$sp " "$SP "
                "$fp " "$FP "
                "$ra " "$RA ";
    return 0;
}
